# Generated by Django 5.2.14 on 2026-06-15 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0002_mesa_pedido_itempedido'),
    ]

    operations = [
        migrations.CreateModel(
            name='CodigoVerificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefono', models.CharField(max_length=20, unique=True)),
                ('codigo', models.CharField(max_length=8)),
                ('creado_en', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
