# Generated by Django 5.2.16 on 2026-07-15 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0003_codigoverificacion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itempedido',
            name='observacion',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='permite_comanda_especial',
        ),
        migrations.AddField(
            model_name='mesa',
            name='cliente_telefono',
            field=models.CharField(blank=True, default=None, max_length=20, null=True),
        ),
    ]
